/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.DICHVU.gui_registration;
import Global.DataGlobal;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JPanel;

/**
 *
 * @author manhh
 */
public class ViewMain extends javax.swing.JFrame {
    private DataGlobal dataGlobal;
    /**
     * Creates new form ViewMain
     */
    public ViewMain(DataGlobal dataGlobal) {
        this.dataGlobal = dataGlobal;
        
        initComponents();
        GUI_DICHVU();
    }
    public void addComponent(JPanel father, JPanel child) {
        father.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.CENTER;
        father.add(child, gbc);
    }
    public void GUI_DICHVU() {
        // init component
        gui_registration registration = new gui_registration(this.dataGlobal, this);
        // add component
        if (Global.Global_variable.role_name == "staff") {
            addComponent(panel_dangki, registration);
        }
        else {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        NhanSu = new javax.swing.JPanel();
        CaTruc = new javax.swing.JPanel();
        GuiXe = new javax.swing.JPanel();
        DichVu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelDichVu = new javax.swing.JTabbedPane();
        panel_dangki = new javax.swing.JPanel();
        panel_thanhtoan = new javax.swing.JPanel();
        panel_loaidichvu = new javax.swing.JPanel();
        panel_giadichvuThang = new javax.swing.JPanel();
        panel_gialuot = new javax.swing.JPanel();
        panel_loaiphuongtien = new javax.swing.JPanel();
        panel_khungthoigian = new javax.swing.JPanel();
        panel_thongkedoanhthu = new javax.swing.JPanel();
        ThongKe = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("PHẦN MỀM QUẢN LÝ GỬI XE Ở CHUNG CƯ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("PTITHCM - NHẬP MÔN CÔNG NGHỆ PHẦN MỀM");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("D22CQCN02-N. ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(231, 231, 231))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NhanSuLayout = new javax.swing.GroupLayout(NhanSu);
        NhanSu.setLayout(NhanSuLayout);
        NhanSuLayout.setHorizontalGroup(
            NhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        NhanSuLayout.setVerticalGroup(
            NhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Nhân Sự", NhanSu);

        javax.swing.GroupLayout CaTrucLayout = new javax.swing.GroupLayout(CaTruc);
        CaTruc.setLayout(CaTrucLayout);
        CaTrucLayout.setHorizontalGroup(
            CaTrucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        CaTrucLayout.setVerticalGroup(
            CaTrucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ca Trực", CaTruc);

        javax.swing.GroupLayout GuiXeLayout = new javax.swing.GroupLayout(GuiXe);
        GuiXe.setLayout(GuiXeLayout);
        GuiXeLayout.setHorizontalGroup(
            GuiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        GuiXeLayout.setVerticalGroup(
            GuiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gửi Xe", GuiXe);

        javax.swing.GroupLayout panel_dangkiLayout = new javax.swing.GroupLayout(panel_dangki);
        panel_dangki.setLayout(panel_dangkiLayout);
        panel_dangkiLayout.setHorizontalGroup(
            panel_dangkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        panel_dangkiLayout.setVerticalGroup(
            panel_dangkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        panelDichVu.addTab("Đăng kí", panel_dangki);

        javax.swing.GroupLayout panel_thanhtoanLayout = new javax.swing.GroupLayout(panel_thanhtoan);
        panel_thanhtoan.setLayout(panel_thanhtoanLayout);
        panel_thanhtoanLayout.setHorizontalGroup(
            panel_thanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        panel_thanhtoanLayout.setVerticalGroup(
            panel_thanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        panelDichVu.addTab("Thanh toán", panel_thanhtoan);

        javax.swing.GroupLayout panel_loaidichvuLayout = new javax.swing.GroupLayout(panel_loaidichvu);
        panel_loaidichvu.setLayout(panel_loaidichvuLayout);
        panel_loaidichvuLayout.setHorizontalGroup(
            panel_loaidichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        panel_loaidichvuLayout.setVerticalGroup(
            panel_loaidichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        panelDichVu.addTab("Loại dịch vụ", panel_loaidichvu);

        javax.swing.GroupLayout panel_giadichvuThangLayout = new javax.swing.GroupLayout(panel_giadichvuThang);
        panel_giadichvuThang.setLayout(panel_giadichvuThangLayout);
        panel_giadichvuThangLayout.setHorizontalGroup(
            panel_giadichvuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        panel_giadichvuThangLayout.setVerticalGroup(
            panel_giadichvuThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        panelDichVu.addTab("Giá dịch vụ theo tháng", panel_giadichvuThang);

        javax.swing.GroupLayout panel_gialuotLayout = new javax.swing.GroupLayout(panel_gialuot);
        panel_gialuot.setLayout(panel_gialuotLayout);
        panel_gialuotLayout.setHorizontalGroup(
            panel_gialuotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        panel_gialuotLayout.setVerticalGroup(
            panel_gialuotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        panelDichVu.addTab("Giá lượt", panel_gialuot);

        javax.swing.GroupLayout panel_loaiphuongtienLayout = new javax.swing.GroupLayout(panel_loaiphuongtien);
        panel_loaiphuongtien.setLayout(panel_loaiphuongtienLayout);
        panel_loaiphuongtienLayout.setHorizontalGroup(
            panel_loaiphuongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        panel_loaiphuongtienLayout.setVerticalGroup(
            panel_loaiphuongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        panelDichVu.addTab("Các loại phương tiện", panel_loaiphuongtien);

        javax.swing.GroupLayout panel_khungthoigianLayout = new javax.swing.GroupLayout(panel_khungthoigian);
        panel_khungthoigian.setLayout(panel_khungthoigianLayout);
        panel_khungthoigianLayout.setHorizontalGroup(
            panel_khungthoigianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        panel_khungthoigianLayout.setVerticalGroup(
            panel_khungthoigianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        panelDichVu.addTab("Các khung thời gian", panel_khungthoigian);

        javax.swing.GroupLayout panel_thongkedoanhthuLayout = new javax.swing.GroupLayout(panel_thongkedoanhthu);
        panel_thongkedoanhthu.setLayout(panel_thongkedoanhthuLayout);
        panel_thongkedoanhthuLayout.setHorizontalGroup(
            panel_thongkedoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        panel_thongkedoanhthuLayout.setVerticalGroup(
            panel_thongkedoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        panelDichVu.addTab("Thống kê doanh thu", panel_thongkedoanhthu);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDichVu, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDichVu)
        );

        javax.swing.GroupLayout DichVuLayout = new javax.swing.GroupLayout(DichVu);
        DichVu.setLayout(DichVuLayout);
        DichVuLayout.setHorizontalGroup(
            DichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DichVuLayout.setVerticalGroup(
            DichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dịch Vụ", DichVu);

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1203, Short.MAX_VALUE)
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống Kê", ThongKe);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CaTruc;
    private javax.swing.JPanel DichVu;
    private javax.swing.JPanel GuiXe;
    private javax.swing.JPanel NhanSu;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane panelDichVu;
    private javax.swing.JPanel panel_dangki;
    private javax.swing.JPanel panel_giadichvuThang;
    private javax.swing.JPanel panel_gialuot;
    private javax.swing.JPanel panel_khungthoigian;
    private javax.swing.JPanel panel_loaidichvu;
    private javax.swing.JPanel panel_loaiphuongtien;
    private javax.swing.JPanel panel_thanhtoan;
    private javax.swing.JPanel panel_thongkedoanhthu;
    // End of variables declaration//GEN-END:variables
}
